### ISSUE TITLE
DTPP

### ISSUE THREAD

**Issue by StephenGordan** [MCZhi/GameFormer-Planner#11]
DTPP will be open source? Or has TPP been open sourced?
Is DTPP your latest work?

**Comment by StephenGordan** [comment]
Does the Scenario Tree（the output of transformer decoder) include the trajectory of the self-driving car?

**Comment by MCZhi** [comment]
Hi, @StephenGordan, thank you for your interest. Yes, DTPP will be available as open source and included in [tuplan_garage](https://github.com/autonomousvision/tuplan_garage). In the meantime, you can refer to the code of TPP [here](https://github.com/NVlabs/spline-planner). The scenario tree does not include the trajectory of the SDC because its future trajectory is already generated by the ego trajectory sampler.

**Comment by StephenGordan** [comment]
Thank you very much.！
DTPP is not open source yet, right? When will it be? 
DTPP should be your job, why is it included in tuplan_garage? 
Is the structure of DTPP likely to be the development direction of learning based palnner?

**Comment by MCZhi** [comment]
I will do my best to make it available in late February. DTPP will be included in the model zoo in tuplan_garage; however, the code will be released on my side. I believe that DTPP has the potential to be utilized in commercial vehicles, and I hope it can become a direction of learning-based planning.
