### ISSUE TITLE
visualization problem

### ISSUE THREAD

**Issue by SupOne11** [MCZhi/GameFormer-Planner#20]
Thank you for sharing. I would like to ask what might be the problem when, after running the run_nuplan_test file, there are no error messages and a test_log folder is created, but the nuboard that pops up is empty?

![Screenshot from 2024-05-17 18-06-23](https://github.com/MCZhi/GameFormer-Planner/assets/92090033/78a81c96-3157-44ce-ae98-1c3739b5e267)

**Comment by FlyEgle** [comment]
I have the same problem, are you solution it ?

**Comment by MCZhi** [comment]
Can you try directly launching the nuBoard from the command line?
`python nuplan-devkit/nuplan/planning/script/run_nuboard.py simulation_path=/your/path`

**Comment by FlyEgle** [comment]
I have solve this issue;
1. Copy the nuborad folder and config folder to Gameformer-planner proj;
2. run the python Gamefromer-planner/run_board.py simulation_path=[xxx/xxx.nuboard]
No show the visual result because of the pickle can not load the gameformer-planner planner module.So need move the nuboard folder to proj
